### PR TITLE
Port to GNAT Community 2020

### PR DESCRIPTION
**Pull request by jquorning**

### CODE REVIEW

**Comment by jquorning** [comment]
Danke merci tak

**Comment by Lucretia** [comment]
I want [this](https://groups.google.com/d/msg/comp.lang.ada/v2hV4MR9r3Y/C8I6laV3AQAJ) confirming first before I do anything.

**Comment by Fabien-Chouteau** [comment]
TM 13.1 (9.1/3) : An operational item that directly specifies an aspect of an entity shall appear before the entity is frozen (see 13.14)

http://www.ada-auth.org/standards/12rm/html/RM-13-1.html

**Comment by Lucretia** [comment]
Superceded by #58

**Pull request closed without merging**
