### PR TITLE
Fix build with GNAT 2020

### PR DESCRIPTION
**Pull request by mosteo**
This is a minimal untested fix. I do not know how to easily test this part of the library.

### CODE REVIEW

**Comment by mosteo** [comment]
Nevermind, this is a duplicate of a queued PR with a better fix.

**Comment by Lucretia** [comment]
So, there was nothing wrong with this code?

**Comment by mosteo** [comment]
Sorry, I was unclear. The queued PR #62 addresses the same problem. I don't know which of the gnats is right here, but the problem still exists with current CE2020.

**Comment by Lucretia** [comment]
Ok, thanks for the clarification, may as well keep this open just in case.

**Comment by anisimkov** [comment]
the patch #62 (and the same #75) are better fixing the same issue.

**Comment by Lucretia** [comment]
Fixed with Commit 45731de64ee18ffd561d36204feeeac2c477c659

**Pull request closed without merging**
