### PR TITLE
Support SDL2_Mixer

### PR DESCRIPTION
**Pull request by jquorning**
SDL2_Mixer can be found here: https://www.libsdl.org/projects/SDL_mixer/

### CODE REVIEW

**Comment by Lucretia** [comment]
You don't need the extra gpr files, like image and ttf, mixer should go into the main sdlada.gpr, same for the tests (put them into tests.gpr)

**Comment by jquorning** [comment]
But SDL2_Mixer is a separate library like ttf and image. Would it not be more clean to take ttf/image out of sdlada.gpr? Otherwise the user would have to install mixer/ttf/image to use basic subprograms. Note SDL2 has audio functions, some of them are called mix-something. SDL2_Mixer is a separate library.

**Comment by Lucretia** [comment]
Actually, I did originally have ttf and image as separate libs, but in the end decided to just merge them. I can separate them though.

**Comment by Lucretia** [comment]
What does "Import SDL.Mixer from other project" mean? What other project?

**Comment by Lucretia** [comment]
> What does "Import SDL.Mixer from other project" mean? What other project?

Same question for the other import mentioned above, examples.

**Comment by Lucretia** [comment]
ping

**Comment by jquorning** [comment]
I think I had a separate mixer project before it was imported the SDLada branch.

**Pull request closed without merging**
