### PR TITLE
Utf8

### PR DESCRIPTION
**Pull request by docandrew**
I've made a few additions in this branch and also fixed the issue with keycodes using the wrong OR-ed value. This is my first time submitting a pull request to another project, so please let me know if I've goofed anything up. I tried hard to use the same style as I saw in the existing project.

One problem - I made changes to my Makefile to get it to build on my Windows machine (commit 2b65aa9), and I have no idea how to remove that commit from the branch so it doesn't interfere with the rest of the project. I think you may be able to cherry-pick the other commits out if you decide to merge. If you have any advice for how to correct this, please let me know!

Very Respectfully,
   Jon

### CODE REVIEW

**Comment by Lucretia** [comment]
Hi,

Yeah, I saw your mail and started looking at that mask, took me a while to remember where I got it from. Then VSCode decided to just die for no reason, so I dunno. Anyway, yeah I think you're right on that one, should be 4000_0000 (1<<30) and not 2000_0000 (1<<29), obviously a typo. I'll get that fixed.

**Comment by Lucretia** [comment]
I really want to get this windows crap sorted tbf. Mingw is a Unix-like build, so surely it has sdl2-config? What you have there will likely break someone else's windows build. Can you post what sdl2-config outputs for --cflags and --libs? Ta.

**Comment by docandrew** [comment]
The mingw distro for SDL2 had the sdl2-config tool, but it expects you to install in /opt/local.

```
$ ./sdl2-config --cflags --libs
-I/opt/local/x86_64-w64-mingw32/include/SDL2 -Dmain=SDL_main
-L/opt/local/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2 -mwindows
```

If you're doing everything inside a Cygwin environment I think it would be fine, but I was trying hard to use the GNAT-bundled gcc/mingw to keep everything the same as I was using to build SDLAda itself with.

I played around for a couple hours trying to weasel the SDL libs into the GNAT distro folder so the build would "just work" (minus changing the backslashes - that's probably the one thing that must be changed for Windows), but I eventually gave up and just hard-coded the extracted library locations into the SDLAda Makefile and .gpr.

Ironically, I'm using SDLAda to create a build tool that hopefully eliminates some of these problems.

I believe mingw does some funny stuff to re-map it's standard include locations, and GNAT mingw probably goes even further - there may be an easy way to copy the SDL includes and .a files into C:\GNAT\2019\<somewhere> and have the Makefile and .gpr work with few changes.

**Comment by docandrew** [comment]
What I have in my Makefile will <absolutely> break everybody's Windows build. Please don't merge that commit!

**Comment by Lucretia** [comment]
> The mingw distro for SDL2 had the sdl2-config tool, but it expects you to install in /opt/local.

Why? It should be pointing to whatever the  --prefix was when it was installed, from sdl2-config.in:

```
#!/bin/sh

prefix=@prefix@
exec_prefix=@exec_prefix@
exec_prefix_set=no
libdir=@libdir@
```

exec_prefix is set up by configure. So, why does it map to somewhere your SDL2 isn't? Who built your SDL2? If you didn't, why did you install it somewhere where it wasn't supposed to be (/opt/local in your case)?

> ```
> $ ./sdl2-config --cflags --libs
> -I/opt/local/x86_64-w64-mingw32/include/SDL2 -Dmain=SDL_main
> -L/opt/local/x86_64-w64-mingw32/lib -lmingw32 -lSDL2main -lSDL2 -mwindows
> ```

Basically, sdl2-config should just work for any unix-like environment, including mingw, msys2, whatever. If it doesn't, then that's a bug for SDL2.

This just seems very similar to a conversation I had on irc with Fabien about a similar issue, where he was building within alire and there were SDL2 path issues all over due to his custom SDL2 install.

> Ironically, I'm using SDLAda to create a build tool that hopefully eliminates some of these problems.

Alire by any chance?
 
> I believe mingw does some funny stuff to re-map its standard include locations, and GNAT mingw probably goes even further - there may be an easy way to copy the SDL includes and .a files into C:\GNAT\2019<somewhere> and have the Makefile and .gpr work with few changes.

When I used mingw years ago, they always just said to install it in c:\mingw\ or similar. I've not done that in years so I've no idea what they recommend now. Also, msys2 doesn't have a proper working GNAT package, so, IMO, you should be using mingw for FSF GNAT. I've not installed GNAT CE yet.

As for other builds, i.e. Visual Studio using Mingw, that should be doable as Mingw can be used as normal Windows tools AFAIK, i.e. from PowerShell. In that case, creating a (is it still called a sln?) project specifically for that would be fine and hard coding the paths there is ok as well. This wouldn't affect the makefile and shouldn't.

**Comment by Lucretia** [comment]
> What I have in my Makefile will break everybody's Windows build. Please don't merge that commit!

Trust me, I'm not going to.

**Comment by docandrew** [comment]
> exec_prefix is set up by configure. So, why does it map to somewhere your SDL2 isn't? Who built your SDL2? If you didn't, why did you install it somewhere where it wasn't supposed to be (/opt/local in your case)?
> 

I was just using the binary SDL download from the main website. I suspect the right place to drop the SDL libs would have been c:\GNAT\2019\lib\gcc\x86_64-pc-mingw32\8.3.1\, but I'll have to do some experimentation to make sure. In any case, sdl2-config isn't going to know about that.

This is what I mean by funny stuff going on with re-mapping the search directories:

```
PS C:\> C:\GNAT\2019\bin\ld.exe --verbose
GNU ld (GNU Binutils) 2.30.52.20180618
  Supported emulations:
   i386pep
   i386pe
using internal linker script:
==================================================
/* Default linker script, for normal executables */
/* Copyright (C) 2014-2018 Free Software Foundation, Inc.
   Copying and distribution of this script, with or without modification,
   are permitted in any medium without royalty provided the copyright
   notice and this notice are preserved.  */
OUTPUT_FORMAT(pei-x86-64)
SEARCH_DIR("/it/sbx/a2c2/x86_64-windows/binutils-stable-c/pkg/x86_64-pc-mingw32/lib"); SEARCH_DIR("/it/sbx/a2c2/x86_64-windows/binutils-stable-c/pkg/lib"); SEARCH_DIR("/usr/local/lib"); SEARCH_DIR("/lib"); SEARCH_DIR("/usr/lib");
```

> 
> Basically, sdl2-config should just work for any unix-like environment, including mingw, msys2, whatever. If it doesn't, then that's a bug for SDL2.
> 

I'm not using any of those environments - just a standard GNAT CE install.

> This just seems very similar to a conversation I had on irc with Fabien about a similar issue, where he was building within alire and there were SDL2 path issues all over due to his custom SDL2 install.
> 
> > Ironically, I'm using SDLAda to create a build tool that hopefully eliminates some of these problems.
> 
> Alire by any chance?
> 

No, this is a different tool.

**Comment by Lucretia** [comment]
> I was just using the binary SDL download from the main website. I suspect the right place to drop the SDL libs would have been c:\GNAT\2019\lib\gcc\x86_64-pc-mingw32\8.3.1, but I'll have to do some experimentation to make sure. In any case, sdl2-config isn't going to know about that.

I just downloaded their windows archive for mingw. Their sdl2-config points to /opt/local but their makefile install assumes /usr/local. I would send them a bug report on that.

Best thing, grab the sources and build SDL2 yourself. Then check to make sure the generated sdl2-config --libs shows the correct (your prefix dir) for the SDL build.

> This is what I mean by funny stuff going on with re-mapping the search directories:

Various ports do remapping of directories for the gnu toolchain, they always have, even on various Linux distributions, don't know if they still do as most have converged on the same directory layouts now.

**Comment by Lucretia** [comment]
Pushed as per commit fba84f8ec6cf5c6970d57d1e57633496dc038d87

**Pull request closed without merging**
